name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          if [ -d "ios" ]; then
            cd ios
            pod install
          else
            echo "ios directory not found"
            exit 1
          fi

      - name: Clean build
        run: flutter clean

      - name: Build iOS app
        run: flutter build ios --release --no-codesign -v

      - name: Prepare IPA package
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload/Runner.app

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
